In [4]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [0]:
# x = n,m
# y = n,m

x = tf.random.normal(shape=(10, 2))

y = tf.random.normal(shape=(10,2))

In [7]:
tf.matmul(x, y, transpose_a=True)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.8385754,  6.1624393],
       [-1.5577376,  3.5232193]], dtype=float32)>

In [8]:
tf.matmul(x, y, transpose_b=True)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 3.8475115e+00, -1.7197486e+00, -1.6886115e+00,  8.5631800e-01,
         4.4638610e-01, -1.8264720e+00,  8.4523611e-02, -2.5287600e+00,
         1.9925997e-01, -1.7597123e+00],
       [-3.8986676e+00,  1.4323384e+00,  1.3716136e+00, -8.3425933e-01,
        -2.0747633e-01,  1.3395773e+00, -4.2346012e-02,  2.1305957e+00,
        -5.5652016e-01,  1.7096623e+00],
       [ 2.7162251e+00, -9.1456127e-01, -8.6441624e-01,  5.7224852e-01,
         7.8770965e-02, -7.9596025e-01,  1.7869528e-02, -1.3683970e+00,
         4.8299932e-01, -1.1714001e+00],
       [ 1.8333666e+00, -3.6338678e-01, -3.0566639e-01,  3.5888079e-01,
        -1.4720011e-01, -1.1892610e-01, -2.3374215e-02, -5.7027394e-01,
         6.1620408e-01, -7.3055315e-01],
       [-1.4112020e+00, -2.8203121e-01, -3.7927806e-01, -2.1569285e-01,
         5.5658633e-01, -8.3392805e-01,  9.6387357e-02, -3.4277296e-01,
        -1.1163210e+00,  4.2935780e-01],
       [ 7.1863637e+00, -

In [0]:
x = np.array([[1,2,3], [11,12,13]])

In [14]:
x

array([[ 1,  2,  3],
       [11, 12, 13]])

In [16]:
x.shape

(2, 3)

In [15]:
pd.DataFrame(x)

0   1   2
0   1   2   3
1  11  12  13

In [17]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.633568  , 0.54326594],
       [0.9403363 , 0.6177931 ]], dtype=float32)>

In [18]:
a = np.array([1,2,3])
b = np.array([10,11,12])

np.dot(a, b)

68