In [0]:
%tensorflow_version 2.x

In [43]:
import tensorflow as tf
import numpy as np

print(tf.__version__)


2.1.0


In [0]:
def cn(shape):
  return tf.random.uniform(shape=shape)

Dot

In [45]:
cn((1,2,3))

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0.6344712 , 0.00143898, 0.62833214],
        [0.5539793 , 0.73748004, 0.92854273]]], dtype=float32)>

In [46]:
cn(())

<tf.Tensor: shape=(), dtype=float32, numpy=0.4100032>

In [47]:
cn((1,))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2994976], dtype=float32)>

In [0]:
h_t = cn((2, 5))

In [0]:
h_s = cn((2, 10, 5))

In [50]:
h_t

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.32741344, 0.23500979, 0.7510724 , 0.02727139, 0.45350254],
       [0.30397356, 0.16930878, 0.15401101, 0.54972494, 0.99606335]],
      dtype=float32)>

In [51]:
tf.expand_dims(h_t, 1)

<tf.Tensor: shape=(2, 1, 5), dtype=float32, numpy=
array([[[0.32741344, 0.23500979, 0.7510724 , 0.02727139, 0.45350254]],

       [[0.30397356, 0.16930878, 0.15401101, 0.54972494, 0.99606335]]],
      dtype=float32)>

In [52]:
tf.keras.layers.Dot(axes=[2,2])([h_s, tf.expand_dims(h_t, 1)])

<tf.Tensor: shape=(2, 10, 1), dtype=float32, numpy=
array([[[0.99451697],
        [1.3339211 ],
        [1.2734945 ],
        [1.3178947 ],
        [0.66992456],
        [0.9913914 ],
        [0.68345094],
        [0.7350996 ],
        [0.73045325],
        [1.0788376 ]],

       [[1.7800409 ],
        [1.6289743 ],
        [1.0820072 ],
        [0.9113463 ],
        [1.5005991 ],
        [1.1579604 ],
        [1.2224853 ],
        [1.0992975 ],
        [1.5686407 ],
        [1.1172118 ]]], dtype=float32)>

In [0]:
# tf.keras.layers.Dot()


In [0]:
lambda_layer = tf.keras.layers.Lambda(lambda x: x / tf.sqrt(5.))

a = tf.keras.layers.Dot(axes=[2,2])([h_s, tf.expand_dims(h_t, 1)])

In [57]:
lambda_layer(a)

<tf.Tensor: shape=(2, 10, 1), dtype=float32, numpy=
array([[[0.4447615 ],
        [0.5965476 ],
        [0.56952405],
        [0.58938044],
        [0.29959938],
        [0.44336373],
        [0.30564854],
        [0.32874653],
        [0.32666862],
        [0.48247084]],

       [[0.7960585 ],
        [0.7284995 ],
        [0.4838883 ],
        [0.40756646],
        [0.67108834],
        [0.51785564],
        [0.54671204],
        [0.49162078],
        [0.70151746],
        [0.4996323 ]]], dtype=float32)>

In [60]:
lambda_layer(a).numpy()[0] * np.sqrt(5.)

array([[0.99451697],
       [1.333921  ],
       [1.2734945 ],
       [1.3178947 ],
       [0.6699246 ],
       [0.9913914 ],
       [0.68345094],
       [0.7350996 ],
       [0.73045325],
       [1.0788376 ]], dtype=float32)

General


In [63]:
W = tf.keras.layers.Dense(10, use_bias=False)
h_t = cn((2, 10))
h_s = cn((2, 2, 10))

h_t = tf.expand_dims(h_t, 1)

print(h_t)
print('--')
print(h_s)


tf.Tensor(
[[[0.45266664 0.04404461 0.18038714 0.21367955 0.98357356 0.9210954
   0.57213247 0.6208191  0.88815653 0.9645945 ]]

 [[0.07507002 0.31131268 0.9815351  0.6511189  0.23003137 0.21522844
   0.6592015  0.8323045  0.0236032  0.08606887]]], shape=(2, 1, 10), dtype=float32)
--
tf.Tensor(
[[[0.3944713  0.8068278  0.30078125 0.8338939  0.64477384 0.25733387
   0.60756946 0.47692454 0.6787455  0.9644903 ]
  [0.5174563  0.9337163  0.44643342 0.6294148  0.13423026 0.38760936
   0.9332154  0.04603827 0.7119391  0.9888127 ]]

 [[0.00732768 0.48578012 0.42734826 0.8636693  0.32627368 0.48024905
   0.8578795  0.9146699  0.4715278  0.4205475 ]
  [0.4186983  0.9879868  0.10260558 0.25076807 0.8468759  0.2788006
   0.25673628 0.62596583 0.9017602  0.9434488 ]]], shape=(2, 2, 10), dtype=float32)


In [64]:
weighted_hs = W(h_s)

weighted_hs

<tf.Tensor: shape=(2, 2, 10), dtype=float32, numpy=
array([[[-1.0784218 ,  0.0843946 ,  0.3434191 , -0.4668903 ,
         -0.22317803, -0.44731852,  0.12177296,  0.01029599,
          0.9581102 ,  0.6899247 ],
        [-1.5116608 , -0.17268515,  0.08132295, -0.5818126 ,
          0.00272454, -0.30131075,  0.42392927, -0.20122361,
          0.85521543,  0.6468315 ]],

       [[-0.81531155,  0.05771962,  0.4225064 , -0.04262423,
          0.03843369, -0.00847203,  0.13009594,  0.27891314,
          1.1032917 ,  0.98326313],
        [-1.0194542 ,  0.10388352,  0.43577668, -0.5981662 ,
         -0.46313584, -0.42587772, -0.07105876,  0.14094833,
          0.81692874,  0.5314339 ]]], dtype=float32)>

In [67]:
h_t.shape

TensorShape([2, 1, 10])

In [69]:
tf.keras.layers.Dot(axes=[2,2])([weighted_hs, h_t])

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[ 0.43871176],
        [ 0.4247232 ]],

       [[ 0.77930194],
        [-0.06864227]]], dtype=float32)>

In [74]:
weighted_hs.numpy()

array([[[-1.0784218 ,  0.0843946 ,  0.3434191 , -0.4668903 ,
         -0.22317803, -0.44731852,  0.12177296,  0.01029599,
          0.9581102 ,  0.6899247 ],
        [-1.5116608 , -0.17268515,  0.08132295, -0.5818126 ,
          0.00272454, -0.30131075,  0.42392927, -0.20122361,
          0.85521543,  0.6468315 ]],

       [[-0.81531155,  0.05771962,  0.4225064 , -0.04262423,
          0.03843369, -0.00847203,  0.13009594,  0.27891314,
          1.1032917 ,  0.98326313],
        [-1.0194542 ,  0.10388352,  0.43577668, -0.5981662 ,
         -0.46313584, -0.42587772, -0.07105876,  0.14094833,
          0.81692874,  0.5314339 ]]], dtype=float32)

In [77]:
h_t.numpy().shape

(2, 1, 10)

In [80]:
tf.matmul(weighted_hs, h_t, transpose_b=True)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[ 0.43871176],
        [ 0.4247232 ]],

       [[ 0.77930194],
        [-0.06864227]]], dtype=float32)>