In [1]:
!pip install tensorflow-gpu

     |████████████████████████████████| 421.8MB 39kB/s 
     |████████████████████████████████| 3.8MB 46.3MB/s 
     |████████████████████████████████| 450kB 45.5MB/s 
     |████████████████████████████████| 81kB 12.2MB/s 
ERROR: tensorflow 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.1.0 which is incompatible.
ERROR: tensorflow 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.1.0 which is incompatible.
ERROR: tensorboard 2.1.0 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found exis

In [0]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [0]:
x = tf.range(10)

In [3]:
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [0]:
dataset = tf.data.Dataset.from_tensor_slices(x)

In [5]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [6]:
for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [0]:
dataset = dataset.repeat(3)

In [8]:
dataset

<RepeatDataset shapes: (), types: tf.int32>

In [9]:
for i in dataset:
  print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype

In [0]:
dataset = dataset.batch(7)

In [11]:
dataset

<BatchDataset shapes: (None,), types: tf.int32>

In [12]:
for i in dataset:
  print(i)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [0]:
dataset = dataset.map(lambda x: x * 2)

In [14]:
dataset

<MapDataset shapes: (None,), types: tf.int32>

In [15]:
for i in dataset:
  print(i)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
tf.Tensor([16 18], shape=(2,), dtype=int32)


In [19]:
dataset = dataset.apply(tf.data.experimental.unbatch())

<_UnbatchDataset shapes: (), types: tf.int32>

In [20]:
dataset

<_UnbatchDataset shapes: (), types: tf.int32>

In [21]:
for i in dataset:
  print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, sh

In [0]:
dataset = dataset.filter(lambda x: x< 10)

In [23]:
dataset

<FilterDataset shapes: (), types: tf.int32>

In [24]:
for i in dataset:
  print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [0]:
dataset = tf.data.Dataset.range(10).shuffle(buffer_size=100)

# If buffer size is 100, it means that Tensorflow will keep a buffer of the next 100 samples, and will randomly select one those 100 samples

# Buffer size = 1 <- no shuffle

# From hands on book, I requires to set the buffer size as large enough <- so the shuffle may be effective, just don't set exceed the RAM size & exceed the dataset size

In [50]:
dataset

<ShuffleDataset shapes: (), types: tf.int64>

In [51]:
for i in dataset:
  print(i)

tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)


Testing with california housing data

In [0]:
# check with pandas 

df = pd.read_csv('housing.csv')

In [55]:
display(df.head())
print(df.shape)

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

(20640, 10)


In [0]:
dataset = tf.data.TextLineDataset('housing.csv')

In [57]:
dataset

<TextLineDatasetV2 shapes: (), types: tf.string>

In [59]:
counter = 0
for i in dataset:
  print(i)

  counter += 1
  if counter == 5:
    break

tf.Tensor(b'longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity', shape=(), dtype=string)
tf.Tensor(b'-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY', shape=(), dtype=string)
tf.Tensor(b'-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY', shape=(), dtype=string)
tf.Tensor(b'-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY', shape=(), dtype=string)
tf.Tensor(b'-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY', shape=(), dtype=string)


In [0]:
dataset = tf.data.TextLineDataset('housing.csv').skip(1)

In [61]:
counter = 0
for i in dataset:
  print(i)

  counter += 1
  if counter == 5:
    break

tf.Tensor(b'-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY', shape=(), dtype=string)
tf.Tensor(b'-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY', shape=(), dtype=string)
tf.Tensor(b'-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY', shape=(), dtype=string)
tf.Tensor(b'-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY', shape=(), dtype=string)
tf.Tensor(b'-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY', shape=(), dtype=string)


Load multiple data files

In [0]:
!split -C 1000 /content/housing.csv

In [0]:
TRAIN_FILEPATHS = '/content/x*'

In [0]:
filepath_dataset = tf.data.Dataset.list_files(TRAIN_FILEPATHS, seed=42)

In [120]:
n_reader = 5
dataset = filepath_dataset.interleave(
    lambda filepath : tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_reader
)

Cause: could not parse the source code:

    lambda filepath : tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_reader

This error may be avoided by creating the lambda in a standalone statement.

Cause: could not parse the source code:

    lambda filepath : tf.data.TextLineDataset(filepath).skip(1), cycle_length=n_reader

This error may be avoided by creating the lambda in a standalone statement.



In [121]:
dataset

<InterleaveDataset shapes: (), types: tf.string>

In [0]:
counter = 0
for i in dataset:
  print(i)

  counter += 1
  if counter == 50:
    break

# Preprocessing the Data

In [0]:
record_defaults = [0, np.nan, tf.constant(np.nan, dtype=tf.float64), 'Hello', tf.constant([])]

In [76]:
record_defaults

[0,
 nan,
 <tf.Tensor: shape=(), dtype=float64, numpy=nan>,
 'Hello',
 <tf.Tensor: shape=(0,), dtype=float32, numpy=array([], dtype=float32)>]

In [0]:
parsed_files = tf.io.decode_csv('1,2,3,4,5', record_defaults)

In [78]:
parsed_files

[<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'4'>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>]

In [84]:
df.describe().loc[['mean', 'std'], :]

longitude   latitude  ...  median_income  median_house_value
mean -119.569704  35.631861  ...       3.870671       206855.816909
std     2.003532   2.135952  ...       1.899822       115395.615874

[2 rows x 9 columns]

In [0]:
X_mean = df.describe().loc['mean', :].values
X_std = df.describe().loc['std', :].values

In [110]:
df.shape

(20640, 10)

In [111]:
df.head()

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [0]:
test_data = df.iloc[0, :].values

In [168]:
test_data.tolist()

[-122.23,
 37.88,
 41.0,
 880.0,
 129.0,
 322.0,
 126.0,
 8.3252,
 452600.0,
 'NEAR BAY']

In [170]:
record_defaults = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'hello']

tf.io.decode_csv('-122.23, 37.88, 41.0, 880.0, 129.0, 322.0, 126.0, 8.3252, 452600.0, NEAR BAY', record_defaults=record_defaults)

[<tf.Tensor: shape=(), dtype=float32, numpy=-122.23>,
 <tf.Tensor: shape=(), dtype=float32, numpy=37.88>,
 <tf.Tensor: shape=(), dtype=float32, numpy=41.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=880.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=129.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=322.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=126.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=8.3252>,
 <tf.Tensor: shape=(), dtype=float32, numpy=452600.0>,
 <tf.Tensor: shape=(), dtype=string, numpy=b' NEAR BAY'>]

In [0]:
@tf.function  # tensorflow decorator
def preprocess(line):
  X_mean = df.describe().loc['mean', :].values
  X_std = df.describe().loc['std', :].values
  n_inputs= 9
  # defs = [[0.] * n_inputs + [tf.constant([], dtype=tf.float32), ['a'] + [tf.constant([], dtype=tf.string)]]]
  defs = [tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.float32),
         tf.constant([], dtype=tf.string)]

  fields = tf.io.decode_csv(line, defs)
  # return fields
  x = tf.stack(fields[:-2])
  x_cat = tf.stack(fields[-1:])
  y = tf.stack(fields[-2:-1])

  return (x - X_mean) / X_std, x_cat, y

In [157]:
counter = 0
for i in dataset:
  print(i)

  counter += 1
  if counter == 2:
    break

tf.Tensor(b'-117.37,33.19,38.0,861.0,213.0,486.0,204.0,4.1875,185000.0,NEAR OCEAN', shape=(), dtype=string)
tf.Tensor(b'-116.66,33.09,24.0,1378.0,272.0,532.0,188.0,1.5909,221900.0,INLAND', shape=(), dtype=string)


In [172]:
dataset = dataset.map(preprocess)

0        -122.23     37.88  ...         8.3252            452600.0
1        -122.22     37.86  ...         8.3014            358500.0
2        -122.24     37.85  ...         7.2574            352100.0
3        -122.25     37.85  ...         5.6431            341300.0
4        -122.25     37.85  ...         3.8462            342200.0
...          ...       ...  ...            ...                 ...
20635    -121.09     39.48  ...         1.5603             78100.0
20636    -121.21     39.49  ...         2.5568             77100.0
20637    -121.22     39.43  ...         1.7000             92300.0
20638    -121.32     39.43  ...         1.8672             84700.0
20639    -121.24     39.37  ...         2.3886             89400.0

[20640 rows x 9 columns]> appears to be a generator function. It will not be converted by AutoGraph.
0        -122.23     37.88  ...         8.3252            452600.0
1        -122.22     37.86  ...         8.3014            358500.0
2        -122.24     37.85 

In [173]:
dataset

<MapDataset shapes: ((), (), (), (), (), (), (), (), (), ()), types: (tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.string)>

In [0]:
dataset = dataset.batch(10)

In [175]:
dataset.prefetch(1)

<PrefetchDataset shapes: ((None,), (None,), (None,), (None,), (None,), (None,), (None,), (None,), (None,), (None,)), types: (tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.string)>

In [177]:
counter = 0
for i in dataset.prefetch(1):
  print(i)

  counter += 1
  if counter == 1:
    break


(<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-119.88, -118.31, -122.04, -122.53, -117.95, -119.88, -118.31,
       -122.02, -122.53, -117.94], dtype=float32)>, <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([34.43, 33.95, 37.12, 37.91, 33.83, 34.43, 33.94, 37.11, 37.9 ,
       33.82], dtype=float32)>, <tf.Tensor: shape=(10,), dtype=float32, numpy=array([14., 44., 30., 37., 31., 16., 43., 36., 44., 34.], dtype=float32)>, <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2472., 2490., 1427., 2524., 2421., 1734., 2104., 2066., 2846.,
       1347.], dtype=float32)>, <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([685., 430., 311., 398., 389., 365., 393., 401., 551., 212.],
      dtype=float32)>, <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1292., 1305.,  686.,  999., 1348.,  962., 1132.,  942., 1232.,
        676.], dtype=float32)>, <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([621., 411., 251., 417., 413., 391., 394., 344., 537., 201.],
      dty

## Getting data from tf keras