In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

Start with data source
construct Dataset 
with uisng 

1) from_tensorfs()

2) rom_tensor_slices()

3) TFRecordDataset()

In [2]:
dataset = tf.data.Dataset.from_tensor_slices([8,3,0,8,2,1])

dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [3]:
for ele in dataset:
  print(ele.numpy())

8
3
0
8
2
1


In [4]:
it = iter(dataset)
print(next(it).numpy())

8


In [5]:
next(it).numpy()

3

In [6]:
dataset.reduce(0, lambda state, value: state + value).numpy()

22

In [0]:
dataset_1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform(shape = (4,10)))

In [10]:
dataset_1

<TensorSliceDataset shapes: (10,), types: tf.float32>

In [11]:
dataset_1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [0]:
# dataset_2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform([4]), tf.random.uniform([4,100], maxval=100, dtype=tf.int32)))
# dataset2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform([4]), tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))
dataset_2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform(shape=(4,)), tf.random.uniform(shape=(4,100), maxval=100, dtype=tf.int32)))

In [30]:
dataset_2

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

In [0]:
dataset3 = tf.data.Dataset.zip((dataset_1, dataset_2))

In [32]:
dataset3

<ZipDataset shapes: ((10,), ((), (100,))), types: (tf.float32, (tf.float32, tf.int32))>

In [0]:
x = tf.SparseTensor(indices=[[0,0], [1,2]], values=[1,2], dense_shape=[3,4])
# the indeiceis is where the value is 
# value is the value for first, indices, second indicies
# dnese shape is the matrix shape

In [0]:
dataset4 = tf.data.Dataset.from_tensor_slices(x)

In [38]:
dataset4

<TensorSliceDataset shapes: (4,), types: tf.int32>

In [42]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))

dataset1

<TensorSliceDataset shapes: (10,), types: tf.int32>

In [44]:
for i in dataset1:
  print(i.numpy())

[3 2 9 2 4 3 4 7 5 9]
[9 9 9 7 2 2 8 7 6 8]
[7 7 8 3 7 4 6 8 1 6]
[5 5 1 5 3 1 7 6 5 4]


reading data from numpy array, use 


```
tf.data.Dataset.from_tensor_slices
```



In [45]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 1s 0us/step


In [0]:
img, label = train

In [0]:
dataset = tf.data.Dataset.from_tensor_slices((img, label))


In [51]:
dataset

<TensorSliceDataset shapes: ((28, 28), ()), types: (tf.uint8, tf.uint8)>

using with python generator

In [0]:
def count(stop):
  i = 0
  while i < stop:
    yield i
    i += 1

In [0]:
x = count(10)

In [55]:
for i in x:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [0]:
ds_count = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes=())

In [59]:
ds_count

<FlatMapDataset shapes: (), types: tf.int32>

In [60]:
for i in ds_count:
  print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(17, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor(19, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(23, shape=(), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)


In [0]:
ds_count = ds_count.repeat().batch(10).take(10)